postgresql:
  restart: always
  image: sameersbn/postgresql:12-20200524
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist
gitlab:
  restart: always
  image: sameersbn/gitlab:14.4.0
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "12080:80"
    - "12022:22"
  environment:
    - DEBUG=false
    - GITLAB_PORT=12080
    - GITLAB_SSH_PORT=12022
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
redis:
  restart: always
  image: sameersbn/redis:latest
  command:
    - --loglevel warning
